name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install and build project
        run: |
          cd client
          npm install
          npm run build

      - name: Install setup and authenticate with pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./setup.sh
      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./digital-ocean-auth.sh $DIGITALOCEAN_TOKEN
