name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  continuous-integration:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install and build project
        run: |
          cd client
          npm install
          npm run build

      - name: Install setup and authenticate with Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./setup.sh

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./digital-ocean-auth.sh $DIGITALOCEAN_TOKEN

  post-merge-actions:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Pulumi and DigitalOcean
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          echo "Performing post-merge actions on main branch"
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./setup.sh
          ./digital-ocean-auth.sh $DIGITALOCEAN_TOKEN

      - name: Build Docker Image
        run: |
          docker-compose build web-next-app

      - name: Tag Docker Image to DigitalOcean Container Registry
        run: |
          docker tag stoix-cloud-saver-web-next-app:latest registry.digitalocean.com/${{ secrets.DOCKER_REGISTRY }}/stoix-cloud-saver-web-next-app
          docker images

      - name: Push Docker Image to DigitalOcean Container Registry
        env:
          DOCKER_REGISTRY: ${{ ecrets.DIGITALOCEAN_TOKEN  }}
        run: |
          cd project_infra
          chmod +x ./scripts/*.sh
          cd scripts
          ./digital-ocean-auth.sh $DIGITALOCEAN_TOKEN
          docker push registry.digitalocean.com/${{ secrets.DOCKER_REGISTRY }}/stoix-cloud-saver-web-next-app
